[project]
name = "adv-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
    "portion>=2.6.1",
    "z3-solver>=4.15.4.0",
]
